#!/usr/bin/env python

# Copyright 2018 Sysdig
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

import os

from cli import cli

if __name__ == '__main__':

    # Remove SDC_TOKEN from environment for consistence
    os.environ.pop('SDC_TOKEN', None)

    # Parse the arguments from the CLI
    args = cli.parse_args()
    if args.subcommand is None:
        cli.print_help()
        exit(1)
    else:
        args.func(args)
        exit(0)
